fix tests/db/model/generator/methods.js flapper (#1110)
* fix collector assignment flappers

tests/db/model/collector/methods.js > instanceMethods > reassignGenerators > reassignGenerators:
      AssertionError: expected '___CollectorthirdCollector' to equal '___CollectorsecondCollector'
      + expected - actual
      -___CollectorthirdCollector
      +___CollectorsecondCollector

      at Promise.resolve.then.then.then.then.spread (tests/db/model/collector/methods.js:296:49)

tests/db/model/generator/methods.js > assignToCollector > collectors specified, first choice available:
     TypeError: Cannot read property 'name' of null
      at generator1.updateWithCollectors.then (tests/db/model/generator/methods.js:89:44)

* trying one more thing here... creating the generators one by one
instead of in parallel... maybe it will still flap... ?